import { Geist, Geist_Mono } from "next/font/google";
import Analytics from "@/components/analytics"; // ✅ use Analytics component
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Analytics /> {/* ✅ Only one source of GA */}
        {children}
      </body>
    </html>
  );
}
// Note: The Analytics component handles all GA logic, so no need for inline scripts here.